using System.Collections.Generic;
using System.Linq;
using System.Numerics;

namespace Solutions.Problem029
{
    public static class V1
    {
        /*
            Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

            22=4, 23=8, 24=16, 25=32
            32=9, 33=27, 34=81, 35=243
            42=16, 43=64, 44=256, 45=1024
            52=25, 53=125, 54=625, 55=3125
            If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

            4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

            How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
        */

        public static int CountDistinctPowers(IEnumerable<int> aEnumerable, IEnumerable<int> bEnumerable)
        {
            var bArr = bEnumerable as int[] ?? new int[0];
            var powers = from a in aEnumerable.ToArray() from b in bArr select BigInteger.Pow(new BigInteger(a), b);

            return powers.Distinct().Count();
        }

        public static int CountIndistinctPowers(IEnumerable<int> aEnumerable, IEnumerable<int> bEnumerable)
        {
            var bArr = bEnumerable as int[] ?? new int[0];
            var powers = from a in aEnumerable.ToArray()
                         from b in bArr
                         select new {a, b, Pow = BigInteger.Pow(new BigInteger(a), b)};
            var group = powers.GroupBy(p => p.Pow).Where(g => g.Count() > 1).Select(g => $"{g.Key}: {string.Join(", ", g.Select(p => $"({p.a}, {p.b})"))}").ToList();
            return 0;
        }
    }
}
